import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import ImageSlider from "@/components/ImageSlider";
import HomeGrid from "@/components/HomeGrid";
import ProductCard from "@/components/ProductCard";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Sporty</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<Navbar />
			<ImageSlider />
			<section className="container mx-auto px-6 my-12">
				<h1 className=" text-2xl sm:text-3xl font-normal my-4 text-center">
					Our Purpose
				</h1>
				<p className="text-gray-500 max-w-2xl text-center mx-auto">
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium
					harum fugiat esse qui, consequuntur veritatis.
				</p>
			</section>
			<HomeGrid />
			<section className="grid-cols-1 px-6 mt-6 mb-20 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 container mx-auto grid gap-6">
				<ProductCard />
				<ProductCard />
				<ProductCard />
				<ProductCard />
				<ProductCard />
				<ProductCard />
				<ProductCard />
			</section>
			<section className="container mx-auto px-6 my-12 flex">
				<div className="text-gray-500 md:w-1/2 text-center md:text-left">
					<h3 className="text-2xl font-semibold text-black">
						Get The Newsletter
					</h3>
					<p className="my-4 ">
						Get great stuff in your inbox, no-nonsense. Only the essentials.
						That’s a promise from us.
					</p>
					<div className="border-b-2 p-1 border-gray-500 flex gap-4">
						<input
							placeholder="Your email address"
							className="outline-0 p-1 w-full  placeholder:text-gray-500"
							type="email"
						/>
						<button className="w-fit font-semibold text-gray-800">
							SUBSCRIBE
						</button>
					</div>
				</div>
				<div className="md:w-1/2 mt-12 h-fit my-auto flex justify-around md:justify-center font-semibold text-gray-800 gap-4">
					<button className="hover:text-gray-500 duration-300">
						Privacy Policy
					</button>
					<button className="hover:text-gray-500 duration-300">
						Sizing Guide
					</button>
					<button className="hover:text-gray-500 duration-300">FAQ</button>
				</div>
			</section>{" "}
			<Footer />
		</>
	);
}
